# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               The Pursuit of Wellness 
tagline:             'searching in the world of medicine'
description:         'I''ve been experiencing unexplained chronic pain and fatigue for several years, and in this blog  I''ll detail what I learn as I delve into medical literature to find a diagnosis that the medical system failed to provide. I''d love to hear from you at wellseeker01@gmail.com.'
url:                 http://something.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Sam Ritter 
  url:               something.github.io 
  email:             sritter88@gmail.com

# Custom vars
version:             1.0.0
myfooter:            "---  \n I'd love to hear from you, email me at <wellseeker01@gmail.com>. \n  \n---  \n  \nReferences and Notes"
 

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
analytics :
  provider : google
  google : 
      tracking_id : 'UA-71605009-1'
  getclicky :
    site_id :
