# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               The Pursuit of Wellness 
tagline:             'tackling the world of medicine'
description:         'I''m a grad student who has been suffering from unexplained chronic pain and fatigue for several years. On these pages I''ll detail what I learn as I delve into medical literature to find a diagnosis that the medical system failed to provide.'
url:                 http://something.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Sam Ritter 
  url:               something.github.io 
  email:             sritter88@gmail.com

# Custom vars
version:             1.0.0
