gems: [jekyll-paginate]
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               The Pursuit of Wellness 
tagline:             'searching in the world of medicine'
description:         'A blog about the medical knowledge I gain as I delve into research literature to find the cause of year-spanning pain and fatigue. I''d love to hear from you at wellseeker01@gmail.com.'
url:                 http://something.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Sam Ritter 
  url:               something.github.io 
  email:             sritter88@gmail.com

# Custom vars
version:             1.0.0
myfooter:            "---  \n I'd love to hear from you, email me at <wellseeker01@gmail.com>. \n  \n---  \n  \nReferences and Notes"
 

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
analytics :
  provider : google
  google : 
      tracking_id : 'UA-71605009-1'
  getclicky :
    site_id :
